### ISSUE TITLE
Info aggiuntive

### ISSUE THREAD

**Issue by PaulusThe1** [muchasuerte/ha-besmart#3]
Ciao, Andrea. Sto usando il tuo progetto (fantastico) per gestire su HomeAssistant il mio termostato BeSmart.
due info:
1) vorrei monitorare quante ore è acceso il riscaldamento. Sto usando un nuovo sensore derivato da climate ma mi serve sapere quale stato assume il"climate" quando la caldaia è accesa.
2) si può monitorare lo stato della batteria del termostato?

Grazie mille e complimenti per il progetto

**Comment by faxbio** [comment]
Ciao, io per monitorare quel che chiedi tu ho impostato un sensore template basato sull hvac_action che diventa "heating" quando la caldaia e' accesa (in realta' io ho 2 termostati quindi lo verifico su entrambi)
`    hvac_flame:
       value_template: >
          {% if is_state_attr('climate.besmart_casa_nuova', 'hvac_action', 'heating') %}
          on
          {% elif is_state_attr('climate.besmart_casa_vecchia', 'hvac_action', 'heating') %}
          on
          {% else %}
          off
          {% endif %}
      friendly_name: Caldaia Accesa`

per il punto 2 ho appena sottomesso qui ad Andrea (che ringrazio anche io per il progetto) la richiesta di merge per il codice modificato perche' l'attuale non estrae lo status della batteria. se dovesse tardare il merge puoi copiare la modifica e mettertela su, e' solo 1 riga di codice.

**Comment by muchasuerte** [comment]
Ciao, 

@faxbio  grazie per la modifica l'ho appena approvata.

@PaulusThe1 per monitorare l'accensione uso un binary_sensor.heating ed uso un "Grafico Storico" per verificare quando è acceso, forse quello della batteria dovrei rivederlo a seguito della modifica integrata.

```
binary_sensor:
  - platform: template
    sensors:
      heating:
        friendly_name: "Heating"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'hvac_action') == 'heating' }}"
      cooling:
        friendly_name: "Cooling"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'hvac_action') == 'cooling' }}"
      thermostat_status:
        friendly_name: "Thermostat status"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'heating_state') == true }}"
      battery_state:
        friendly_name: "battery state"
        device_class: battery
        value_template: "{{ state_attr('climate.besmart_thermostat', 'battery_state') == '1' }}"
        icon_template: mdi:battery
```
